export const tempDailyFixtures = [
  {
    fixture: {
      id: 868168,
      referee: "Michael Oliver, England",
      timezone: "UTC",
      date: "2023-02-11T15:00:00+00:00",
      timestamp: 1676127600,
      periods: {
        first: 1676127600,
        second: null,
      },
      venue: {
        id: 525,
        name: "Selhurst Park",
        city: "London",
      },
      status: {
        long: "First Half",
        short: "1H",
        elapsed: 10,
      },
    },
    league: {
      id: 39,
      name: "Premier League",
      country: "England",
      logo: "https://media.api-sports.io/football/leagues/39.png",
      flag: "https://media.api-sports.io/flags/gb.svg",
      season: 2022,
      round: "Regular Season - 23",
    },
    teams: {
      home: {
        id: 52,
        name: "Crystal Palace",
        logo: "https://media.api-sports.io/football/teams/52.png",
        winner: null,
      },
      away: {
        id: 51,
        name: "Brighton",
        logo: "https://media.api-sports.io/football/teams/51.png",
        winner: null,
      },
    },
    goals: {
      home: 0,
      away: 0,
    },
    score: {
      halftime: {
        home: 0,
        away: 0,
      },

      fulltime: {
        home: null,
        away: null,
      },
      extratime: {
        home: null,
        away: null,
      },
      penalty: {
        home: null,
        away: null,
      },
    },
  },
  {
    fixture: {
      id: 868169,
      referee: "Andy Madley, England",
      timezone: "UTC",
      date: "2023-02-11T15:00:00+00:00",
      timestamp: 1676127600,
      periods: {
        first: 1676127600,
        second: null,
      },
      venue: {
        id: 535,
        name: "Craven Cottage",
        city: "London",
      },
      status: {
        long: "First Half",
        short: "1H",
        elapsed: 9,
      },
    },
    league: {
      id: 39,
      name: "Premier League",
      country: "England",
      logo: "https://media.api-sports.io/football/leagues/39.png",
      flag: "https://media.api-sports.io/flags/gb.svg",
      season: 2022,
      round: "Regular Season - 23",
    },
    teams: {
      home: {
        id: 36,
        name: "Fulham",
        logo: "https://media.api-sports.io/football/teams/36.png",
        winner: null,
      },
      away: {
        id: 65,
        name: "Nottingham Forest",
        logo: "https://media-3.api-sports.io/football/teams/65.png",
        winner: null,
      },
    },
    goals: {
      home: 0,
      away: 0,
    },
    score: {
      halftime: {
        home: 0,
        away: 0,
      },
      fulltime: {
        home: null,
        away: null,
      },
      extratime: {
        home: null,
        away: null,
      },
      penalty: {
        home: null,
        away: null,
      },
    },
  },
];
